### ISSUE TITLE
favicon.ico not found

### ISSUE THREAD

**Issue by RHRRD** [reverendhomer/CourseWork2015#2]
I got the message

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

at the main page. Can we fix that?

**Comment by mkmkme** [comment]
Cannot reproduce that on my machine. And also Google tell us that `Favicon stands for "Favorites Icon". It's the little icon beside your site's name in the favorites list, before the URL in the address bar and bookmarks folder and as a bookmarked website on the desktop in some operating systems.`
so I think that's not critical.
